name: SQL Linter

on: 
  push:
    branches: LW-11

jobs:
  SQLLinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code in repo
        uses: "actions/checkout@v3"
      - name: Start SQL linter
        run: |
          pip install sqlfluff
          sqlfluff lint $GITHUB_WORKSPACE/DataSchema.sql --dialect postgres
