name: Program Code Linter
on:
  push: 
    branches: LW-11

jobs: 
  ProgramCodeLinter:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code in repo
        uses: actions/checkout@v3
      - name: Lint program code
        uses: github/super-linter@v4
        env:
          VALIDATE_KOTLIN: true
          FILTER_REGEX_INCLUDE: ./*.kt
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
